version: '2.0'
services: 
  pdss-utilities-mysql:
    container_name: pdss-utilities-mysql8
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    platform: linux/x86_64
    volumes:
      - ~/opt/dockerMysql8:/var/lib/mysql
  pdss-utilities-php:
    container_name: pdss-utilities-php7.3
    build: .
    environment:
      #  XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9000 remote_enable=1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1 start_with_request=yes
    volumes: 
      - ..:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports: 
      - "80:80"
      - "5522:5522"
    platform: linux/x86_64